### ISSUE TITLE
Typescript doesn't show up as a language option for `cfn init`

### ISSUE THREAD

**Issue by rnhurt** [aws-cloudformation/cloudformation-cli-typescript-plugin#62]
I'm trying to build a CloudFormation resource in Typescript.  So, I followed the directions [here](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/what-is-cloudformation-cli.html#resource-type-setup) and in this repository.  Everything looked like it installed properly but I don't see an option for Typescript when I run `cfn init`.  All I see are go, java, python36, python37.

```
Do you want to develop a new resource(r) or a module(m) or a hook(h)?.
>> r
What's the name of your resource type?
(Organization::Service::Resource)
>> asdf::asfd::asfda
Select a language for code generation:
[1] go
[2] java
[3] python36
[4] python37
(enter an integer):
```

I've uninstalled and reinstalled "cloudformation-cli" multiple times, in multiple ways: brew, pip, etc. but I can't get a Typescript option.

**Comment by PatMyron** [comment]
Believe it only shows languages you already have the plugin installed for. Do you have `cloudformation-cli-typescript-plugin` installed before running that?
